[package]
name = "strata-mantle-acceptance"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[dev-dependencies]
mantle-artifact = { path = "../mantle-artifact" }
mantle-runtime = { path = "../mantle-runtime" }
strata = { path = "../strata" }

[lib]
name = "strata_mantle_acceptance"
path = "src/lib.rs"
