use crate::model::{EvidenceClass, Feature, requirements::*};

const COMPONENT_COMPOSITION_REPORT_REQUIREMENTS: &[EvidenceClass] = &[
    EvidenceClass::ParserCoverage,
    EvidenceClass::CheckerValidation,
    EvidenceClass::CheckedIrLowering,
    EvidenceClass::CompositionReport,
    EvidenceClass::ArtifactAdmission,
    EvidenceClass::RuntimeExecution,
    EvidenceClass::Diagnostics,
    EvidenceClass::RunnableExample,
    EvidenceClass::PositiveTest,
    EvidenceClass::NegativeTest,
    EvidenceClass::SourceToRuntimeGate,
    EvidenceClass::FuzzSeed,
    EvidenceClass::BoundedOrProperty,
    EvidenceClass::PerformanceSmoke,
    EvidenceClass::Documentation,
];

const TARGET_REQUIREMENTS_REQUIREMENTS: &[EvidenceClass] = &[
    EvidenceClass::ParserCoverage,
    EvidenceClass::CheckerValidation,
    EvidenceClass::CheckedIrLowering,
    EvidenceClass::ArtifactAdmission,
    EvidenceClass::RuntimeExecution,
    EvidenceClass::Diagnostics,
    EvidenceClass::RunnableExample,
    EvidenceClass::PositiveTest,
    EvidenceClass::NegativeTest,
    EvidenceClass::SourceToRuntimeGate,
    EvidenceClass::FuzzSeed,
    EvidenceClass::BoundedOrProperty,
    EvidenceClass::PerformanceSmoke,
    EvidenceClass::Documentation,
];

pub(crate) const FEATURES: &[Feature] = &[
    feature!(
        "typed-component-protocol-port-boundaries",
        "Typed component, protocol, and port communication boundaries",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/boundary_contracts.rs", "parser_accepts_protocol_port_component_and_send_via"),
            CheckerValidation => ("crates/strata/src/language/tests/boundary_contracts.rs", "checker_rejects_send_port_without_process_authority"),
            CheckedIrLowering => ("crates/strata/src/language/tests/boundary_contracts.rs", "checker_builds_typed_boundary_ids_and_lowering_tables"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/boundary_tables.rs", "validate_accepts_declared_boundary_tables"),
            RuntimeExecution => ("crates/mantle-runtime/src/tests/boundary_runtime.rs", "runtime_traces_declared_boundary_send"),
            Diagnostics => ("docs/src/diagnostics.md", "port ... is not declared"),
            RunnableExample => ("examples/boundary_contracts_main.str", "send worker via WorkerPort Work"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/boundary_contracts.rs", "boundary_contracts_check_build_run_and_trace_typed_port"),
            NegativeTest => ("crates/mantle-artifact/src/tests/boundary_tables.rs", "validate_rejects_send_port_without_process_authority"),
            SourceToRuntimeGate => ("Justfile", "examples/boundary_contracts_main.str"),
            FuzzSeed => ("fuzz/seeds/strata_source_program_check_lower/boundary_contracts.strpack", "send worker via WorkerPort Work"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/boundary_contracts.mta", "protocol.0.required_authority.kind=protocol_boundary"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/boundary_contracts.str", "send worker via WorkerPort Work"),
            BoundedOrProperty => ("crates/strata/src/language/tests/boundary_contracts.rs", "bounded_boundary_sets_lower_deterministically"),
            Documentation => ("docs/src/language-surface-assurance.md", "Typed protocol, port, and component boundaries are recorded"),
        ],
    ),
    feature!(
        "checked-component-composition-admission",
        "Checked local component port-binding composition admission",
        Current,
        RuntimeBehavior,
        COMPONENT_COMPOSITION_REPORT_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/component_composition.rs", "parser_accepts_component_imports_and_composition"),
            CheckerValidation => ("crates/strata/src/language/tests/component_composition.rs", "checker_builds_typed_composition_graph_and_lowers_metadata"),
            CheckedIrLowering => ("crates/strata/src/language/tests/component_composition.rs", "artifact.compositions[0].port_bindings[0].importer"),
            CompositionReport => ("crates/strata/src/language/composition_report.rs", "admission_result"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/boundary_tables.rs", "validate_accepts_checked_component_composition_metadata"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/component_composition.rs", "component_composition_checks_builds_runs_and_admits_typed_graph"),
            Diagnostics => ("docs/src/diagnostics.md", "composition ... instance ... component ... import port ... is not bound"),
            RunnableExample => ("examples/component_composition_main.str", "composition AppComposition"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/component_composition.rs", "component_composition_checks_builds_runs_and_admits_typed_graph"),
            PositiveTest => ("crates/strata/src/language/tests/composition_report.rs", "json_report_matches_checked_schema_facts"),
            NegativeTest => ("crates/strata/src/language/tests/component_composition.rs", "checker_rejects_unbound_component_import"),
            NegativeTest => ("crates/strata/src/language/tests/component_composition.rs", "checker_rejects_composition_without_process_port_authority"),
            NegativeTest => ("crates/strata/src/language/tests/component_composition.rs", "checker_rejects_bad_composition_bindings"),
            NegativeTest => ("crates/strata/src/cli.rs", "composition_report_format_parser_rejects_unknown_format"),
            NegativeTest => ("crates/mantle-artifact/src/tests/boundary_tables.rs", "validate_rejects_bad_composition_binding_edges"),
            NegativeTest => ("crates/mantle-artifact/src/tests/codec/decode_failures.rs", "decode_rejects_unbounded_composition_counts_before_allocation"),
            SourceToRuntimeGate => ("Justfile", "examples/component_composition_main.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/component_composition.str", "module component_composition_seed"),
            FuzzSeed => ("fuzz/seeds/strata_source_program_check_lower/component_composition.strpack", "bind main imports WorkerPort -> worker exports WorkerPort"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/component_composition.mta", "composition.0.port_binding.0.imported_port=0"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/component_composition_unbound_import.mta", "composition.0.port_binding_count=0"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/component_composition.str", "emit \"composed worker handled Work\""),
            BoundedOrProperty => ("crates/strata/src/language/tests/component_composition.rs", "bounded_composition_graphs_lower_deterministically"),
            BoundedOrProperty => ("crates/strata/src/language/tests/component_composition.rs", "bounded_composition_reports_are_deterministic"),
            PerformanceSmoke => ("crates/strata-mantle-acceptance/tests/performance_smoke.rs", "component_composition_main.check_lower"),
            PerformanceSmoke => ("crates/strata-mantle-acceptance/tests/performance_smoke.rs", "component_composition_main.composition_report"),
            Documentation => ("docs/src/language-surface-assurance.md", "Checked local component port-binding composition admission is recorded"),
        ],
    ),
    feature!(
        "checked-ir-and-typed-id-boundary",
        "Checked IR and lowering preserve typed IDs across the boundary",
        Current,
        CheckerLowering,
        TYPED_BOUNDARY_REQUIREMENTS,
        [
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/boundary_ownership.rs", "strata_lowering_consumes_checked_type_ids_not_source_type_refs"),
            CheckedIrLowering => ("crates/strata/src/language/tests/process_refs.rs", "!encoded.contains(\"target_process=Worker\")"),
            Diagnostics => ("docs/src/runtime-traces.md", "Do not treat labels as runtime dispatch keys"),
            PositiveTest => ("crates/strata/src/language/tests/nested_pattern_destructuring/basic_patterns.rs", "constructor names must not be lowered as record-field executable references"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/boundary_ownership.rs", "Mantle-owned crates must stay language-neutral"),
            Documentation => ("docs/src/runtime-traces.md", "Do not treat labels as runtime dispatch keys"),
        ],
    ),
    feature!(
        "mantle-artifact-admission",
        "Mantle artifact identity, decoding, and admission",
        Current,
        ArtifactAdmission,
        BOUNDARY_REQUIREMENTS,
        [
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/decode_failures.rs", "decode_rejects_unbounded_process_count_before_allocation"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/identity_admission.rs", "runtime_rejects_loaded_invalid_artifact_identity_before_artifact_loaded"),
            Diagnostics => ("docs/src/artifact-runtime-boundary.md", "Mantle admits artifacts through validation, not filename trust"),
            PositiveTest => ("crates/mantle-artifact/src/tests/codec/round_trip.rs", "artifact_round_trips_and_validates_magic"),
            NegativeTest => ("crates/mantle-artifact/src/tests/identity_and_labels/artifact_limits_and_metadata.rs", "validate_treats_debug_names_as_metadata_not_targets"),
            Documentation => ("docs/src/file-types.md", "Mantle Target Artifact"),
        ],
    ),
    feature!(
        "loaded-runtime-validation",
        "Loaded-runtime validation before runtime side effects",
        Current,
        ArtifactAdmission,
        BOUNDARY_REQUIREMENTS,
        [
            ArtifactAdmission => ("crates/mantle-runtime/src/program/admission.rs", "validate_loaded_artifact_identity"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/state_message_admission/action_admission.rs", "runtime_rejects_loaded_spawn_inside_runtime_if_branch_before_artifact_loaded"),
            Diagnostics => ("docs/src/artifact-runtime-boundary.md", "`ArtifactLoaded` or executing runtime side effects"),
            PositiveTest => ("crates/mantle-runtime/src/run/tests/state_message_admission/action_admission.rs", "runtime_accepts_loaded_for_each_inside_runtime_if_branch"),
            NegativeTest => ("crates/mantle-runtime/src/run/tests/state_message_admission/next_state_templates.rs", "runtime_rejects_loaded_unadmitted_template_state_before_artifact_loaded"),
            Documentation => ("docs/src/artifact-runtime-boundary.md", "Mantle validates loaded"),
        ],
    ),
    feature!(
        "runtime-target-requirements",
        "Runtime target requirements and feature declaration",
        Current,
        RuntimeBehavior,
        TARGET_REQUIREMENTS_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/target_requirements.rs", "module target_requirements_basic"),
            CheckerValidation => ("crates/strata/src/language/tests/target_requirements.rs", "lowering_declares_typed_target_requirements_for_basic_runtime_effects"),
            CheckedIrLowering => ("crates/strata/src/language/tests/target_requirements.rs", "lowering_declares_typed_requirements_for_boundary_composition"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/target_requirements.rs", "validate_accepts_sorted_typed_target_requirements"),
            RuntimeExecution => ("crates/mantle-runtime/src/tests/runtime_boundaries.rs", "runtime_rejects_unsupported_target_feature_before_artifact_loaded"),
            Diagnostics => ("docs/src/diagnostics.md", "target runtime feature ... is not supported by this Mantle runtime"),
            RunnableExample => ("examples/component_composition_main.str", "composition AppComposition"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/component_composition.rs", "gate.target_requirements"),
            NegativeTest => ("crates/mantle-runtime/src/tests/runtime_boundaries.rs", "RuntimeFeature::RemoteSpawn"),
            SourceToRuntimeGate => ("Justfile", "examples/component_composition_main.str"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/component_composition.mta", "target_requirements.feature.0=bounded_mailbox"),
            BoundedOrProperty => ("crates/mantle-artifact/src/tests/target_requirements.rs", "target_requirements_canonicalize_feature_insertion_order"),
            BoundedOrProperty => ("crates/strata/src/language/tests/target_requirements.rs", "lowering_target_requirements_are_deterministic_across_source_declaration_order"),
            PerformanceSmoke => ("crates/strata-mantle-acceptance/tests/performance_smoke.rs", "component_composition_main.target_requirements"),
            Documentation => ("docs/src/language-surface-assurance.md", "Runtime feature declaration and target binding"),
        ],
    ),
];
