use crate::model::{Feature, requirements::*};

pub(crate) const FEATURES: &[Feature] = &[
    feature!(
        "process-init-step-results",
        "Process declarations, init, step, and terminal results",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/examples.rs", "parses_and_checks_actor_ping"),
            CheckerValidation => ("crates/strata/src/language/tests/examples.rs", "parses_and_lowers_panic_step_result"),
            CheckedIrLowering => ("crates/strata/src/language/tests/examples.rs", "StepResult::Panic"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/round_trip.rs", "artifact_round_trips_panic_step_result"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "\"result\":\"Continue\""),
            Diagnostics => ("docs/src/diagnostics.md", "step body must return Stop"),
            RunnableExample => ("examples/actor_sequence.str", "return Continue"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_sequence_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/mantle-runtime/src/tests/actor_host.rs", "in_memory_host_fails_closed_for_panic_without_replay"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_sequence.str"),
            Documentation => ("docs/src/language-reference.md", "| Transition result |"),
        ],
    ),
    feature!(
        "init-whole-body-match",
        "Process init whole-body match",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "init_match_checks_builds_and_runs_on_mantle"),
            CheckerValidation => ("crates/strata/src/language/tests/init_matching.rs", "checks_payload_bearing_enum_variants_in_init_match_when_binding_is_unused"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "target/strata/init_match.mta"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "let artifact = gate.read_artifact(\"target/strata/init_match.mta\")"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "init match selected WarmReady"),
            Diagnostics => ("docs/src/diagnostics.md", "init match must handle variant"),
            RunnableExample => ("examples/init_match.str", "match Warm"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "init_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/init_matching.rs", "rejects_missing_init_match_arm"),
            SourceToRuntimeGate => ("Justfile", "examples/init_match.str"),
            Documentation => ("docs/src/language-reference.md", "fieldless enum matches in `init`"),
        ],
    ),
    feature!(
        "init-return-match",
        "Process init return-match expressions",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/init_matching.rs", "checks_return_match_expression_in_init_body"),
            CheckerValidation => ("crates/strata/src/language/tests/init_matching.rs", "checks_return_match_expression_in_init_body"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "target/strata/init_return_match.mta"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "let artifact = gate.read_artifact(\"target/strata/init_return_match.mta\")"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "init return match selected WarmReady"),
            Diagnostics => ("docs/src/diagnostics.md", "init return match ..."),
            RunnableExample => ("examples/init_return_match.str", "return match Warm"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "init_return_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/init_matching.rs", "rejects_missing_init_return_match_arm"),
            SourceToRuntimeGate => ("Justfile", "examples/init_return_match.str"),
            Documentation => ("docs/src/language-reference.md", "`init return match` arms must be statement-free"),
        ],
    ),
    feature!(
        "step-parameter-patterns",
        "Step parameter patterns",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/step_dispatch_success.rs", "step_signature_destructures_record_list_and_map_payloads"),
            CheckerValidation => ("crates/strata/src/language/tests/nested_pattern_destructuring/step_signature_dispatch.rs", "step_signature_same_message_split_preserves_nested_record_list_and_map_bindings"),
            CheckedIrLowering => ("crates/strata/src/language/tests/nested_pattern_destructuring/step_signature_dispatch.rs", "payload_guard"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/message_payloads.rs", "validate_accepts_payload_guarded_transitions_as_typed_artifact_metadata"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/payload_dispatch.rs", "actor_payload_split_signature_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "step second parameter must be a message constructor pattern or wildcard pattern"),
            RunnableExample => ("examples/actor_payload_split_signature.str", "Envelope(Assign(Ready))"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/payload_dispatch.rs", "actor_payload_split_signature_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/nested_pattern_destructuring/step_signature_dispatch.rs", "rejects_duplicate_step_signature_same_message_nested_predicate"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_payload_split_signature.str"),
            Documentation => ("docs/src/language-reference.md", "step parameter patterns"),
        ],
    ),
    feature!(
        "whole-body-match-msg",
        "Whole-body match msg dispatch",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/nested_pattern_destructuring/match_msg_dispatch.rs", "match_msg_same_message_split_preserves_nested_record_list_and_map_bindings"),
            CheckerValidation => ("crates/strata/src/language/tests/nested_pattern_destructuring/match_msg_dispatch.rs", "match_msg_dispatches_same_message_by_disjoint_fieldless_nested_predicates"),
            CheckedIrLowering => ("crates/strata/src/language/tests/nested_pattern_destructuring/match_msg_dispatch.rs", "payload_guard"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/message_payloads.rs", "validate_accepts_payload_guarded_transitions_as_typed_artifact_metadata"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/payload_dispatch.rs", "actor_payload_split_match_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "match body must be the whole function body"),
            RunnableExample => ("examples/actor_payload_split_match.str", "match msg"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/payload_dispatch.rs", "actor_payload_split_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/nested_pattern_destructuring/match_msg_dispatch.rs", "rejects_guarded_and_unguarded_match_msg_same_message_overlap"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_payload_split_match.str"),
            Documentation => ("docs/src/language-reference.md", "whole-body `match msg`"),
        ],
    ),
    feature!(
        "whole-body-match-state",
        "Whole-body match state dispatch",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/nested_pattern_destructuring/basic_patterns.rs", "state_match_binds_nested_constructor_record_payload"),
            CheckerValidation => ("crates/strata/src/language/tests/state_match_payload_split/disjoint_routing.rs", "state_match_dispatches_same_message_by_disjoint_fieldless_nested_predicates"),
            CheckedIrLowering => ("crates/strata/src/language/tests/step_dispatch_success.rs", "state_match_destructures_record_list_and_map_payloads"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/message_payloads.rs", "validate_accepts_payload_guarded_transitions_as_typed_artifact_metadata"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/payload_dispatch.rs", "actor_payload_state_match_split_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "pattern ... overlaps an earlier pattern for the same typed payload shape"),
            RunnableExample => ("examples/actor_payload_state_match_split.str", "match state"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/payload_dispatch.rs", "actor_payload_state_match_split_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/state_match_payload_split/overlap_rejections.rs", "rejects_guarded_and_unguarded_state_match_same_message_overlap"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_payload_state_match_split.str"),
            Documentation => ("docs/src/language-reference.md", "whole-body `match state`"),
        ],
    ),
    feature!(
        "step-return-match",
        "Step return-match dispatch",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/process_return_match.rs", "return-match transition should carry a concrete payload guard"),
            CheckerValidation => ("crates/strata/src/language/tests/process_return_match.rs", "return-match transition should carry a concrete payload guard"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "process_return_match_checks_builds_and_runs_on_mantle"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "process return-match transition should have a payload guard"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "process_return_match_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "step return match scrutinee"),
            RunnableExample => ("examples/process_return_match.str", "return match phase"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "process_return_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/process_return_match.rs", "rejects_step_return_match_over_direct_state"),
            SourceToRuntimeGate => ("Justfile", "examples/process_return_match.str"),
            Documentation => ("docs/src/language-reference.md", "step return-match expressions"),
        ],
    ),
    feature!(
        "message-dispatch-patterns",
        "Step parameter, match-msg, state-match, and step return-match dispatch",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/nested_pattern_destructuring/basic_patterns.rs", "match_msg_binds_nested_constructor_record_list_and_map_values"),
            CheckerValidation => ("crates/strata/src/language/tests/process_return_match.rs", "return-match transition should carry a concrete payload guard"),
            CheckedIrLowering => ("crates/strata/src/language/tests/nested_pattern_destructuring/step_signature_dispatch.rs", "step_signature_same_message_split_preserves_nested_record_list_and_map_bindings"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/message_payloads.rs", "validate_accepts_payload_guarded_transitions_as_typed_artifact_metadata"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/payload_dispatch.rs", "actor_payload_state_match_split_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "pattern ... overlaps an earlier pattern"),
            RunnableExample => ("examples/actor_payload_state_match_split.str", "match state"),
            PositiveTest => ("crates/strata/src/language/tests/state_match_payload_split/disjoint_routing.rs", "state_match_dispatches_same_message_by_disjoint_fieldless_nested_predicates"),
            NegativeTest => ("crates/strata/src/language/tests/state_match_payload_split/overlap_rejections.rs", "rejects_guarded_and_unguarded_state_match_same_message_overlap"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_payload_state_match_split.str"),
            Documentation => ("docs/src/language-reference.md", "| Pattern dispatch |"),
        ],
    ),
    feature!(
        "explicit-effects-and-authority",
        "Explicit emit, spawn, and send effect usage",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/effects.rs", "rejects_unknown_effect_name"),
            CheckerValidation => ("crates/strata/src/language/tests/effects.rs", "rejects_send_without_declared_effect"),
            CheckedIrLowering => ("crates/strata/src/language/tests/examples.rs", "CheckedAction::Spawn"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/action_effects.rs", "validate_rejects_action_without_declared_effect"),
            RuntimeExecution => ("crates/mantle-runtime/src/tests/runtime_boundaries.rs", "runtime_rejects_action_without_declared_effect"),
            Diagnostics => ("docs/src/diagnostics.md", "uses effect ... but does not declare it"),
            RunnableExample => ("examples/actor_emit_spawn_send.str", "emit \"main authorized worker\""),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/process_refs_and_authority.rs", "actor_emit_spawn_send_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/effects.rs", "rejects_unused_declared_effect"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_emit_spawn_send.str"),
            Documentation => ("docs/src/language-reference.md", "| Effects |"),
        ],
    ),
    feature!(
        "local-spawn-authority",
        "Typed local spawn authority and Mantle admission",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/spawn_authority.rs", "accepts_exact_spawn_authority_for_dynamic_local_spawn"),
            CheckerValidation => ("crates/strata/src/language/tests/spawn_authority.rs", "rejects_spawn_without_matching_authority"),
            CheckedIrLowering => ("crates/strata/src/language/tests/spawn_authority.rs", "CheckedCapabilityDescriptor::Spawn"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/spawn_authority.rs", "validate_rejects_spawn_site_referencing_unknown_authority"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/spawn_authority.rs", "validate_rejects_unused_spawn_site_even_when_authority_matches"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/decode_failures.rs", "decode_rejects_unknown_spawn_authority_kind"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/spawn_authority_runtime.rs", "runtime_spawn_outcome_returns_denied_before_acceptance"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/spawn_authority_admission.rs", "runtime_rejects_loaded_spawn_site_referencing_unknown_authority_before_artifact_loaded"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/spawn_authority_admission.rs", "runtime_rejects_unused_loaded_spawn_site_before_artifact_loaded"),
            Diagnostics => ("docs/src/diagnostics.md", "spawn target ... requires authority"),
            RunnableExample => ("examples/effect_outcome_spawn_denied.str", "authority spawn_worker: Cap<Spawn<Worker>>"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "effect_outcomes_check_build_run_and_return_denied_before_spawn_acceptance"),
            NegativeTest => ("crates/strata/src/language/tests/spawn_authority.rs", "rejects_spawn_with_authority_for_different_target"),
            NegativeTest => ("crates/strata/src/language/tests/spawn_authority.rs", "rejects_unused_spawn_authority_descriptor"),
            SourceToRuntimeGate => ("Justfile", "examples/effect_outcome_spawn_denied.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/effect_outcome_spawn_denied.str", "module effect_outcome_spawn_denied"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/effect_outcome_spawn_denied.mta", "process.0.authority.0.kind=spawn"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/effect_outcome_spawn_denied_malformed_authority_kind.mta", "process.0.authority.0.kind=remote_spawn"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/effect_outcome_spawn_denied.str", "module effect_outcome_spawn_denied"),
            BoundedOrProperty => ("crates/strata/src/language/tests/spawn_authority.rs", "bounded_spawn_authority_models_require_exact_target_descriptor"),
            Documentation => ("docs/src/language-reference.md", "Local Spawn Authority"),
        ],
    ),
    feature!(
        "local-supervision",
        "Typed local supervision and lifecycle semantics",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/local_supervision.rs", "accepts_typed_local_one_for_one_supervision"),
            CheckerValidation => ("crates/strata/src/language/tests/local_supervision.rs", "rejects_duplicate_supervisor_child_names"),
            CheckedIrLowering => ("crates/strata/src/language/tests/local_supervision.rs", "CheckedSendTarget::SupervisorChild"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "ArtifactSpawnKind::LexicalSupervisorChild"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "\"decision\":\"restarted\""),
            Diagnostics => ("docs/src/diagnostics.md", "declares duplicate supervisor child"),
            RunnableExample => ("examples/local_supervision_restart.str", "supervise local one_for_one"),
            RunnableExample => ("examples/local_supervision_inactive_send_outcome.str", "Err(Stopped(Work))"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "local_supervision_restarts_permanent_child_with_new_pid"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "local_supervision_permanent_child_restarts_after_normal_stop"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "local_supervision_transient_child_restarts_after_crash"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "local_supervision_inactive_child_send_outcome_returns_stopped"),
            NegativeTest => ("crates/strata/src/language/tests/local_supervision.rs", "rejects_supervisor_child_target_mismatch"),
            SourceToRuntimeGate => ("Justfile", "examples/local_supervision_restart.str"),
            SourceToRuntimeGate => ("Justfile", "examples/local_supervision_permanent_stop.str"),
            SourceToRuntimeGate => ("Justfile", "examples/local_supervision_inactive_send_outcome.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/local_supervision_restart.str", "module local_supervision_restart"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/local_supervision_restart.mta", "lexical_supervisor_child"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/local_supervision_restart.str", "module local_supervision_restart"),
            BoundedOrProperty => ("crates/mantle-runtime/src/run/tests/supervision.rs", "bounded_restart_intensity_denies_second_restart_within_window"),
            Documentation => ("docs/src/language-reference.md", "Local Supervision"),
        ],
    ),
    feature!(
        "typed-message-payloads",
        "Typed message payloads",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/message_payload_flow.rs", "parses_checks_and_lowers_message_payload_step_binding"),
            CheckerValidation => ("crates/strata/src/language/tests/message_payload_flow.rs", "forwards_payload_binding_through_send"),
            CheckedIrLowering => ("crates/strata/src/language/tests/message_payload_flow.rs", "payload_type()"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/message_payloads.rs", "validate_accepts_payload_message_metadata"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_payloads_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "payload ... has type ..., expected ..."),
            RunnableExample => ("examples/actor_payloads.str", "Assign(Job)"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_payloads_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/message_payload_validation/basic_payloads.rs", "rejects_payload_for_unit_message_variant"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_payloads.str"),
            Documentation => ("docs/src/runtime-reference.md", "typed message parameter"),
        ],
    ),
    feature!(
        "process-instances-and-spawn-routing",
        "Process instances and spawn routing",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_instances_checks_builds_and_runs_on_mantle"),
            CheckerValidation => ("crates/strata/src/language/tests/process_refs.rs", "rejects_duplicate_process_ref_on_same_path"),
            CheckedIrLowering => ("crates/strata/src/language/tests/process_refs.rs", "resolves_process_references_to_ids_before_artifact_encoding"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/process_refs.rs", "validate_rejects_duplicate_process_ref_name"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_instances_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "duplicates process reference id"),
            RunnableExample => ("examples/actor_instances.str", "worker instance handled Ping"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_instances_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/process_refs.rs", "rejects_duplicate_process_ref_on_same_path"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_instances.str"),
            Documentation => ("docs/src/runtime-reference.md", "Lowering emits a process-reference table ID"),
        ],
    ),
    feature!(
        "direct-process-ref-authority",
        "Typed direct ProcessRef authority and payload forwarding",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/process_refs.rs", "resolves_process_references_to_ids_before_artifact_encoding"),
            CheckerValidation => ("crates/strata/src/language/tests/message_payload_process_refs.rs", "forwards_process_ref_payload_through_received_send_target"),
            CheckedIrLowering => ("crates/strata/src/language/tests/process_refs.rs", "!encoded.contains(\"target_process=Worker\")"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/process_ref_payloads.rs", "validate_accepts_process_ref_type_id_at_boundary"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/process_ref_admission.rs", "runtime_rejects_unspawned_process_ref_payload"),
            Diagnostics => ("docs/src/diagnostics.md", "process references must be direct message payloads"),
            RunnableExample => ("examples/actor_reply.str", "ProcessRef<Sink>"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/process_refs_and_authority.rs", "actor_reply_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/mantle-artifact/src/tests/process_ref_payloads.rs", "validate_rejects_nested_process_ref_payload_template"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_reply.str"),
            Documentation => ("docs/src/language-reference.md", "| Process references |"),
        ],
    ),
];
