use crate::model::{Feature, requirements::*};

pub(crate) const FEATURES: &[Feature] = &[
    feature!(
        "runtime-if-control-flow",
        "Mantle-backed runtime if control flow",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/runtime_if_else.rs", "runtime_if_else_checks_and_lowers_to_mantle_control_flow"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_if_else.rs", "runtime_if_else_rejects_non_bool_condition"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_if_else_branches_on_payload_at_mantle_runtime"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/runtime_if_admission.rs", "admission_rejects_if_else_action_nesting_above_limit"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "\"event\":\"branch_selected\""),
            Diagnostics => ("docs/src/diagnostics.md", "statement-level if branches cannot both be empty"),
            RunnableExample => ("examples/runtime_if_else.str", "if (flag == True)"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_if_else_branches_on_payload_at_mantle_runtime"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_rejects_malformed_both_empty_branch_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_if_else.str"),
            Documentation => ("docs/src/syntax-reference.md", "Runtime-bound predicates lower as typed Mantle value templates"),
        ],
    ),
    feature!(
        "runtime-if-payload-projection",
        "Runtime if over received payload record fields",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_branches_on_received_record_field"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "artifact must not dispatch through the source payload alias"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "ArtifactValueTemplate::RecordField"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "\"event\":\"branch_selected\""),
            Diagnostics => ("docs/src/runtime-traces.md", "Mantle selected a typed runtime control-flow branch"),
            RunnableExample => ("examples/runtime_payload_projection_if.str", "assigned_phase == Ready"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_branches_on_received_record_field"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_payload_projection_if.str"),
            Documentation => ("docs/src/examples.md", "runtime_payload_projection_if.str"),
        ],
    ),
    feature!(
        "runtime-if-current-state-projection",
        "Runtime if over current state record fields",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_branches_on_current_record_field"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "assert_current_payload_phase_action_branch"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "ArtifactValueTemplate::RecordField"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_branches_on_current_record_field"),
            Diagnostics => ("docs/src/runtime-traces.md", "Mantle selected a typed runtime control-flow branch"),
            RunnableExample => ("examples/runtime_state_payload_projection_if.str", "held_phase == Ready"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_branches_on_current_record_field"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_state_payload_projection_if.str"),
            Documentation => ("docs/src/examples.md", "runtime_state_payload_projection_if.str"),
        ],
    ),
    feature!(
        "runtime-if-final-next-state",
        "Final-position runtime if next-state selection",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_prefix_selected_next_state_branch"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "assert_final_if_guarded_loop_shape"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "scope\":\"next_state"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_rejects_nested_loop_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_prefix_selected_next_state_branch"),
            Diagnostics => ("docs/src/diagnostics.md", "statement-level if action nesting exceeds maximum depth"),
            RunnableExample => ("examples/runtime_final_if_guarded_loop.str", "enabled == True"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_prefix_selected_next_state_branch"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_rejects_nested_loop_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_final_if_guarded_loop.str"),
            Documentation => ("docs/src/examples.md", "runtime_final_if_guarded_loop.str"),
        ],
    ),
    feature!(
        "runtime-if-noop-branches",
        "Runtime if no-op branches",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_rejects_malformed_both_empty_branch_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            Diagnostics => ("docs/src/diagnostics.md", "statement-level if branches cannot both be empty"),
            RunnableExample => ("examples/runtime_guard_noop.str", "flag == True"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_rejects_malformed_both_empty_branch_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_guard_noop.str"),
            Documentation => ("docs/src/examples.md", "runtime_guard_noop.str"),
        ],
    ),
    feature!(
        "runtime-if-nested-action-branches",
        "Nested runtime if action branches",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "assert_nested_action_branch"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_rejects_action_nesting_above_limit_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            Diagnostics => ("docs/src/diagnostics.md", "runtime if branch cannot bind process references"),
            RunnableExample => ("examples/runtime_nested_if_actions.str", "primary == True"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_rejects_action_nesting_above_limit_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_nested_if_actions.str"),
            Documentation => ("docs/src/examples.md", "runtime_nested_if_actions.str"),
        ],
    ),
    feature!(
        "runtime-for-checked-lists",
        "Mantle-backed bounded runtime for over checked lists",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/validation_rejections.rs", "runtime_for_each_rejects_static_collection_source_folding"),
            CheckedIrLowering => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "CheckedAction::ForEach"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/for_each_admission.rs", "admission_rejects_dynamic_for_each_non_list_collection"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/for_each_payload.rs", "runtime_for_each_iterates_over_payload_at_mantle_runtime"),
            Diagnostics => ("docs/src/diagnostics.md", "for loop collection must be a runtime list binding"),
            RunnableExample => ("examples/runtime_for_each.str", "for item in items"),
            PositiveTest => ("crates/mantle-runtime/src/tests/for_each_host.rs", "in_memory_host_executes_for_each_loop_in_collection_order"),
            NegativeTest => ("crates/mantle-runtime/src/run/tests/state_message_for_each_admission.rs", "runtime_rejects_loaded_dynamic_for_each_non_list_collection_before_artifact_loaded"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_for_each.str"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/collection_state.str", "Map<Phase,Phase,2>"),
            Documentation => ("docs/src/runtime-traces.md", "Runtime Loop Events"),
        ],
    ),
    feature!(
        "runtime-for-loop-branching",
        "Runtime for loop body branching",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_preflights_malformed_loop_bool_before_branch_effects"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            Diagnostics => ("docs/src/runtime-traces.md", "When a branch runs inside a bounded runtime loop body"),
            RunnableExample => ("examples/runtime_for_each_if.str", "for item in items"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_rejects_malformed_branch_send_target_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_for_each_if.str"),
            Documentation => ("docs/src/runtime-traces.md", "Runtime Loop Events"),
        ],
    ),
    feature!(
        "runtime-for-guarded-loops",
        "Runtime if guarded bounded loops",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_preflights_malformed_loop_bool_before_branch_effects"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            Diagnostics => ("docs/src/runtime-traces.md", "When a statement-level branch guards a bounded runtime loop"),
            RunnableExample => ("examples/runtime_guarded_for_each.str", "for item in items"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_rejects_inactive_branch_condition_loop_element_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_guarded_for_each.str"),
            Documentation => ("docs/src/examples.md", "runtime_guarded_for_each.str"),
        ],
    ),
    feature!(
        "runtime-for-received-ref-routing",
        "Runtime for routing through received ProcessRef payloads",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop.rs", "runtime_guarded_ref_loop_routes_received_ref_inside_guarded_loop"),
            CheckerValidation => ("crates/strata/src/language/tests/process_refs.rs", "resolves_process_references_to_ids_before_artifact_encoding"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop.rs", "runtime_guarded_ref_loop_routes_received_ref_inside_guarded_loop"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_guarded_ref_loop_rejects_malformed_received_target_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop_jobs.rs", "runtime_guarded_ref_loop_jobs_routes_payload_values_through_received_ref"),
            Diagnostics => ("docs/src/runtime-reference.md", "process references still remain valid only as direct message payload bindings"),
            RunnableExample => ("examples/runtime_guarded_ref_loop_jobs.str", "Route(ProcessRef<Worker>)"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop_jobs.rs", "runtime_guarded_ref_loop_jobs_routes_payload_values_through_received_ref"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_guarded_ref_loop_rejects_malformed_received_target_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_guarded_ref_loop_jobs.str"),
            Documentation => ("docs/src/examples.md", "runtime_guarded_ref_loop_jobs.str"),
        ],
    ),
    feature!(
        "runtime-for-loop-element-projection",
        "Runtime for loop element record projection",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_routes_ready_phase_through_received_ref"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "is_loop_element_projection_route"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_rejects_unknown_projected_field_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_routes_ready_phase_through_received_ref"),
            Diagnostics => ("docs/src/diagnostics.md", "loop element binding ... cannot have process reference type"),
            RunnableExample => ("examples/runtime_loop_element_projection.str", "routed_phase == Ready"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_routes_ready_phase_through_received_ref"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_rejects_non_record_projection_source_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_loop_element_projection.str"),
            Documentation => ("docs/src/examples.md", "runtime_loop_element_projection.str"),
        ],
    ),
    feature!(
        "return-match-action-blocks",
        "Selected step return-match arms as typed action blocks",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/process_return_match_arm_bounded_assurance/tests.rs", "bounded_assurance_selected_arm_action_blocks_match_checked_ir_and_artifacts"),
            CheckerValidation => ("crates/strata/src/language/tests/process_return_match_arm_bounded_assurance/source.rs", "bounded model sequence"),
            CheckedIrLowering => ("crates/strata/src/language/tests/process_return_match_arm_bounded_assurance/assertions.rs", "checked_action_shapes"),
            ArtifactAdmission => ("crates/strata/src/language/tests/process_return_match_arm_prefix_invalid_templates.rs", "unselected return-match arm send payload template should be validated"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions/return_match_arm_action_block.rs", "process_return_match_arm_action_block_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "step return match arm cannot bind process reference"),
            RunnableExample => ("examples/process_return_match_arm_action_block.str", "return-match action-block uniform prefix"),
            PositiveTest => ("crates/strata/src/language/tests/process_return_match_arm_prefix_properties/tests.rs", "property_generated_selected_arm_action_block_shapes_lower_as_typed_actions"),
            NegativeTest => ("crates/strata/src/language/tests/process_return_match_arm_prefix.rs", "rejects_step_return_match_arm_process_ref_binding"),
            SourceToRuntimeGate => ("Justfile", "examples/process_return_match_arm_action_block.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/process_return_match_arm_action_block.str", "module process_return_match_arm_action_block_seed"),
            BoundedOrProperty => ("Justfile", "bounded-assurance-smoke"),
            Documentation => ("docs/src/development-gates.md", "selected `step return match`"),
        ],
    ),
    feature!(
        "typed-scalar-value-operators",
        "Typed scalar values and value operators",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_scalar_values.rs", "parses_typed_scalar_literals_and_operator_precedence"),
            CheckerValidation => ("crates/strata/src/language/tests/source_scalar_values.rs", "rejects_invalid_scalar_source_forms"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_scalar_values.rs", "lowers_runtime_bound_scalar_operators_as_typed_templates"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/scalar_templates.rs", "admission_accepts_typed_value_if_template"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/scalar_templates.rs", "runtime_evaluates_typed_value_if_template"),
            Diagnostics => ("docs/src/diagnostics.md", "numeric value literals require an explicit scalar suffix"),
            RunnableExample => ("examples/runtime_scalar_priority.str", "fn classify"),
            PositiveTest => ("crates/strata/src/language/tests/source_scalar_values.rs", "folds_concrete_scalar_bindings_records_lists_maps_and_if"),
            NegativeTest => ("crates/strata/src/language/tests/source_scalar_values.rs", "rejects_runtime_bound_static_zero_scalar_divisors"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_scalar_priority.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/runtime_scalar_priority.str", "module runtime_scalar_priority"),
            BoundedOrProperty => ("crates/strata/src/language/tests/source_scalar_bounded.rs", "bounded_scalar_expression_shapes_cover_bindings_collections_and_source_if"),
            Documentation => ("docs/src/language-reference.md", "Scalar Integer Values"),
        ],
    ),
    feature!(
        "source-contract-data-primitives",
        "Immutable String and Bytes source contract data primitives",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_data_primitives.rs", "primitive_literal_display_is_canonical"),
            CheckerValidation => ("crates/strata/src/language/tests/source_data_primitives.rs", "checks_lowers_and_preserves_typed_string_and_bytes_values"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_data_primitives.rs", "condition.left.operand_type_id=1"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/round_trip.rs", "artifact_round_trips_primitive_shapes_and_values"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/scalar_templates.rs", "runtime_uses_primitive_equality_for_branch_selection"),
            Diagnostics => ("docs/src/diagnostics.md", "String literal exceeds maximum primitive data length"),
            RunnableExample => ("examples/source_contract_data_primitives.str", "raw: Bytes"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_data_primitives.rs", "source_contract_data_primitives_check_build_run_preserves_typed_values"),
            NegativeTest => ("crates/strata/src/language/tests/source_data_primitives.rs", "rejects_malformed_and_oversized_primitive_literals"),
            SourceToRuntimeGate => ("Justfile", "examples/source_contract_data_primitives.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/source_contract_data_primitives.str", "module source_contract_data_primitives"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/source_contract_data_primitives_rejected.str", "module source_contract_data_primitives_rejected"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/source_contract_data_primitives.mta", "primitive_type=string"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/source_contract_data_primitives.str", "b\"\\x01\\x02bin\""),
            BoundedOrProperty => ("crates/strata/src/language/tests/source_data_primitives.rs", "concrete_primitive_equality_folds_before_lowering"),
            PerformanceSmoke => ("crates/strata-mantle-acceptance/tests/performance_smoke/profiles.rs", "source_contract_data_primitives.check_lower"),
            PerformanceSmoke => ("crates/strata-mantle-acceptance/tests/performance_smoke/profiles.rs", "source_contract_data_primitives.in_memory_runtime"),
            Documentation => ("docs/src/language-surface-assurance.md", "Source contract data primitives are recorded"),
        ],
    ),
    feature!(
        "typed-effect-outcomes",
        "Typed effect outcomes and commit-or-return boundaries",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/effect_outcomes/branch_patterns.rs", "checks_and_lowers_typed_effect_outcome_bindings_without_source_name_dispatch"),
            CheckerValidation => ("crates/strata/src/language/tests/effect_outcomes/static_rejections.rs", "rejects_spawn_outcome_annotation_without_process_ref_success_shape"),
            CheckedIrLowering => ("crates/strata/src/language/tests/effect_outcomes/branch_patterns.rs", "CheckedAction::SpawnOutcome"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/effect_outcomes.rs", "validate_rejects_spawn_outcome_type_without_process_ref_success"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/effect_outcomes.rs", "validate_rejects_send_outcome_type_without_mailbox_closed_variant"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes.rs", "runtime_spawn_outcome_commits_ok_after_acceptance"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes.rs", "loaded_admission_rejects_send_outcome_type_without_mailbox_closed_variant"),
            Diagnostics => ("docs/src/diagnostics.md", "send outcome binding must have type Result<Unit,SendError<...>>"),
            RunnableExample => ("examples/effect_outcomes.str", "let spawn_result: Result<ProcessRef<Worker>,SpawnError<Unit>> = spawn Worker"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "effect_outcomes_check_build_run_and_bind_typed_commit_results"),
            NegativeTest => ("crates/strata/src/language/tests/effect_outcomes/static_rejections.rs", "rejects_spawn_outcome_as_state_because_success_carries_process_ref"),
            SourceToRuntimeGate => ("Justfile", "examples/effect_outcomes.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/effect_outcomes.str", "module effect_outcomes"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/effect_outcomes.mta", "process.0.transition.0.action.0.kind=spawn_outcome"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/effect_outcomes.str", "module effect_outcomes"),
            BoundedOrProperty => ("crates/strata/src/language/tests/effect_outcomes/static_rejections.rs", "bounded_effect_outcome_state_admission_matches_commit_or_return_model"),
            Documentation => ("docs/src/runtime-reference.md", "Typed Effect Outcomes"),
        ],
    ),
    feature!(
        "source-visible-local-effect-failure-outcomes",
        "Source-visible local effect failure outcomes",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/effect_outcomes/branch_patterns.rs", "checks_and_lowers_typed_effect_outcome_bindings_without_source_name_dispatch"),
            CheckerValidation => ("crates/strata/src/language/tests/effect_outcomes/static_rejections.rs", "rejects_send_outcome_annotation_that_does_not_preserve_target_message_type"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "ArtifactAction::SpawnOutcome"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "ArtifactAction::SendOutcome"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/effect_outcomes.rs", "validate_rejects_send_outcome_type_without_mailbox_closed_variant"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/supervision_send_outcomes.rs", "send_outcome_to_inactive_failed_supervisor_child_returns_crashed"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes/direct_send_failures.rs", "runtime_send_outcome_returns_stopped_after_normal_lifecycle_stop_and_preserves_message"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes/direct_send_failures.rs", "runtime_send_outcome_returns_mailbox_closed_after_supervisor_lifecycle_close"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/supervision_send_outcomes.rs", "send_outcome_to_supervisor_shutdown_child_returns_mailbox_closed"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes.rs", "runtime_spawn_outcome_returns_exhausted_before_acceptance"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes/spawn_failures.rs", "runtime_spawn_outcome_returns_backend_unavailable_before_acceptance"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes.rs", "RuntimeEvent::EffectOutcomeBound"),
            Diagnostics => ("docs/src/diagnostics.md", "invalid --max-runtime-processes value"),
            Diagnostics => ("docs/src/diagnostics.md", "local spawn backend unavailable"),
            RunnableExample => ("examples/effect_outcome_stopped_target.str", "Err(Stopped(Work))"),
            RunnableExample => ("examples/local_supervision_inactive_crashed_send_outcome.str", "Err(Crashed(Work))"),
            RunnableExample => ("examples/effect_outcome_spawn_exhausted.str", "Err(Exhausted(Unit))"),
            RunnableExample => ("examples/effect_outcome_spawn_backend_unavailable.str", "Err(BackendUnavailable(Unit))"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/local_supervision.rs", "local_supervision_inactive_failed_child_send_outcome_returns_crashed"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "effect_outcomes_check_build_run_and_return_stopped_before_acceptance"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "effect_outcomes_check_build_run_and_return_exhausted_before_spawn_acceptance"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "effect_outcomes_check_build_run_and_return_backend_unavailable_before_spawn_acceptance"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "effect_outcomes_check_build_and_fail_closed_when_source_creates_crashed_target"),
            NegativeTest => ("crates/mantle-runtime/src/run/tests/spawn_authority_runtime.rs", "runtime_bare_spawn_backend_unavailable_fails_closed_before_acceptance"),
            NegativeTest => ("crates/mantle-runtime/src/run/tests/supervision.rs", "runtime_local_spawn_backend_unavailable_rejects_supervisor_child_start_before_acceptance"),
            NegativeTest => ("crates/mantle-runtime/src/cli.rs", "run_limits_parser_rejects_zero_runtime_process_limit"),
            SourceToRuntimeGate => ("Justfile", "examples/effect_outcome_stopped_target.str"),
            SourceToRuntimeGate => ("Justfile", "examples/local_supervision_inactive_crashed_send_outcome.str"),
            SourceToRuntimeGate => ("Justfile", "examples/effect_outcome_spawn_exhausted.str"),
            SourceToRuntimeGate => ("Justfile", "examples/effect_outcome_spawn_backend_unavailable.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/effect_outcome_stopped_target.str", "module effect_outcome_stopped_target"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/local_supervision_inactive_crashed_send_outcome.str", "module local_supervision_inactive_crashed_send_outcome"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/effect_outcome_spawn_exhausted.str", "module effect_outcome_spawn_exhausted"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/effect_outcome_spawn_backend_unavailable.str", "module effect_outcome_spawn_backend_unavailable"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/effect_outcome_spawn_backend_unavailable.mta", "BackendUnavailable"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/effect_outcome_stopped_target.str", "module effect_outcome_stopped_target"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/local_supervision_inactive_crashed_send_outcome.str", "module local_supervision_inactive_crashed_send_outcome"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/effect_outcome_spawn_exhausted.str", "module effect_outcome_spawn_exhausted"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/effect_outcome_spawn_backend_unavailable.str", "module effect_outcome_spawn_backend_unavailable"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/valid_effect_outcome_mailbox_closed_backend_unavailable.jsonl", "\"outcome_result\":\"mailbox_closed\""),
            FuzzSeed => ("fuzz/fuzz_targets/mantle_runtime_from_source.rs", "EXHAUSTED_SPAWN_FUZZ_RUN_LIMITS"),
            FuzzSeed => ("fuzz/fuzz_targets/mantle_runtime_from_source.rs", "BACKEND_UNAVAILABLE_SPAWN_FUZZ_RUN_LIMITS"),
            BoundedOrProperty => ("crates/mantle-runtime/src/run/tests/effect_outcomes/direct_send_failures.rs", "runtime_send_outcome_returns_stopped_for_stopped_process_with_open_mailbox"),
            BoundedOrProperty => ("crates/mantle-runtime/src/run/tests/spawn_outcome_supervision.rs", "runtime_spawn_outcome_returns_exhausted_before_supervised_subtree_partial_spawn"),
            Documentation => ("docs/src/runtime-reference.md", "source-to-runtime pre-acceptance send failure outcomes"),
        ],
    ),
    feature!(
        "runtime-observability",
        "Runtime observability trace boundary",
        Current,
        RuntimeBehavior,
        RUNTIME_OBSERVABILITY_REQUIREMENTS,
        [
            RuntimeExecution => ("crates/mantle-runtime/src/tests/runtime_boundaries.rs", "run_artifact_path_writes_trace_for_current_directory_artifact"),
            RuntimeExecution => ("crates/mantle-runtime/src/event/validate.rs", "validate_runtime_trace_jsonl"),
            Diagnostics => ("docs/src/runtime-traces.md", "Runtime dispatch always uses the numeric `message_id`"),
            RunnableExample => ("examples/actor_sequence.str", "actor_sequence"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_sequence_checks_builds_and_runs_on_mantle"),
            PositiveTest => ("crates/mantle-runtime/src/event/validate/tests.rs", "validates_schema_fields_and_runtime_pid_correlation"),
            PositiveTest => ("crates/mantle-runtime/src/event/jsonl/tests.rs", "trace_line_renders_optional_composition_context_only_when_supplied"),
            PositiveTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "validates_optional_composition_correlation_fields"),
            PositiveTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "validates_bound_non_process_supervisor_event_without_component_instance"),
            NegativeTest => ("crates/mantle-runtime/src/tests/runtime_boundaries.rs", "runtime_rejects_trace_limit_exhaustion"),
            NegativeTest => ("crates/mantle-runtime/src/event/validate/tests.rs", "rejects_unknown_runtime_pid_correlation"),
            NegativeTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "rejects_partial_composition_correlation_fields"),
            NegativeTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "rejects_component_instance_on_non_process_scoped_event"),
            NegativeTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "rejects_inconsistent_composition_correlation_fields"),
            NegativeTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "rejects_out_of_range_component_instance_correlation"),
            NegativeTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "rejects_duplicate_component_instance_correlation"),
            NegativeTest => ("crates/mantle-runtime/src/event/validate/composition_context_tests.rs", "rejects_nonzero_composition_deployment_id"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/component_composition.rs", "component_composition_runtime_binding_forgery_fails_before_execution"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_sequence.str"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/component_composition.rs", "component_instance_id"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/valid_composition_context.jsonl", "\"composition_id\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/partial_composition_context.jsonl", "\"component_instance_id\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/non_process_component_context.jsonl", "\"component_instance_id\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/inconsistent_composition_context.jsonl", "\"composition_id\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/nonzero_deployment_context.jsonl", "\"deployment_id\":7"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/out_of_range_composition_component_context.jsonl", "\"component_instance_id\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/duplicate_composition_component_context.jsonl", "\"process_id\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/unknown_pid.jsonl", "\"pid\":9"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/unknown_field.jsonl", "dispatch_key"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/invalid_branch_path.jsonl", "\"branch_path\":[\"0\"]"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/leading_zero_pid.jsonl", "\"pid\":01"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/invalid_enum_value.jsonl", "\"branch\":\"sideways\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/process_id_out_of_range.jsonl", "\"process_id\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/pid_gap.jsonl", "\"pid\":3"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/orphan_spawn_without_parent.jsonl", "\"pid\":2"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/pid_process_id_mismatch.jsonl", "\"process_id\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/payload_pid_process_id_mismatch.jsonl", "\"payload_process_id\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/partial_payload.jsonl", "\"payload_type_id\":2,\"queue_depth\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/missing_entry_spawn.jsonl", "\"process_count\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/missing_schema.jsonl", "\"process_count\":1}"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/branch_path_segment_out_of_range.jsonl", "\"branch_path\":[65536]"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/branch_path_too_long.jsonl", "\"branch_path\":[0,0,0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/branch_path_unknown_segment_encoding.jsonl", "\"branch_path\":[65535]"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/artifact_typed_id_out_of_range.jsonl", "4294967296"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/double_process_terminal.jsonl", "\"event\":\"process_failed\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/new_child_pid_after_stop.jsonl", "\"new_child_pid\":3"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_before_child_terminal.jsonl", "\"module\":\"restart_before_child_terminal\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_count_exceeds_limit.jsonl", "\"restart_window_count\":4"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_not_restarted_nonzero_count.jsonl", "\"restart_window_count\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_restarted_zero_count.jsonl", "\"restart_window_count\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_stale_child_pid.jsonl", "\"module\":\"restart_stale_child_pid\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_unrelated_replacement_parent.jsonl", "\"spawned_by_pid\":3"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_without_child_started.jsonl", "\"module\":\"restart_without_child_started\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_zero_window_limit.jsonl", "\"restart_window_limit\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restart_zero_window_ms.jsonl", "\"restart_window_ms\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restarted_reuses_child_pid.jsonl", "\"new_child_pid\":2"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restarted_without_new_child_pid.jsonl", "\"decision\":\"restarted\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/restarted_without_restart_time_ms.jsonl", "\"restart_time_ms\":null"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/sender_pid_after_stop.jsonl", "\"sender_pid\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/spawned_by_pid_after_stop.jsonl", "\"spawned_by_pid\":1"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/subject_event_after_stop.jsonl", "\"event\":\"message_accepted\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/supervisor_pid_after_stop.jsonl", "\"event\":\"supervisor_child_started\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/valid_effect_outcome_bound.jsonl", "\"event\":\"effect_outcome_bound\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/effect_outcome_spawn_with_message_id.jsonl", "\"message_id\":0"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/valid_basic.jsonl", "\"source_language\":\"strata\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/valid_supervisor_restart.jsonl", "\"module\":\"valid_supervisor_restart\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/valid_supervisor_scope_failure_restart.jsonl", "supervisor_restart_intensity_exceeded"),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/denied_with_new_child_pid.jsonl", "\"decision\":\"denied\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/denied_without_restart_time_ms.jsonl", "\"decision\":\"denied\""),
            FuzzSeed => ("fuzz/seeds/mantle_trace_validate/not_restarted_with_restart_time_ms.jsonl", "\"decision\":\"not_restarted\""),
            BoundedOrProperty => ("crates/mantle-runtime/src/event/jsonl/tests.rs", "rendered_all_event_trace_validates_against_contract"),
            PerformanceSmoke => ("crates/strata-mantle-acceptance/tests/performance_smoke/profiles.rs", "collection_state.jsonl_runtime"),
            PerformanceSmoke => ("crates/strata-mantle-acceptance/tests/performance_smoke/profiles.rs", "component_composition_main.runtime_binding_run"),
            Documentation => ("docs/src/runtime-traces.md", "The trace is evidence that Mantle admitted and executed the artifact"),
            Documentation => ("docs/src/runtime-traces.md", "composition, and component-instance trace fields appear only"),
        ],
    ),
];
