use crate::model::{Feature, requirements::*};

pub(crate) const FEATURES: &[Feature] = &[
    feature!(
        "runtime-if-control-flow",
        "Mantle-backed runtime if control flow",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/runtime_if_else.rs", "runtime_if_else_checks_and_lowers_to_mantle_control_flow"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_if_else.rs", "runtime_if_else_rejects_non_bool_condition"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_if_else_branches_on_payload_at_mantle_runtime"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/runtime_if_admission.rs", "admission_rejects_if_else_action_nesting_above_limit"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "\"event\":\"branch_selected\""),
            Diagnostics => ("docs/src/diagnostics.md", "statement-level if branches cannot both be empty"),
            RunnableExample => ("examples/runtime_if_else.str", "if (flag == True)"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_if_else_branches_on_payload_at_mantle_runtime"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_rejects_malformed_both_empty_branch_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_if_else.str"),
            Documentation => ("docs/src/syntax-reference.md", "Runtime-bound predicates lower as typed Mantle value templates"),
        ],
    ),
    feature!(
        "runtime-if-payload-projection",
        "Runtime if over received payload record fields",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_branches_on_received_record_field"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "artifact must not dispatch through the source payload alias"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "ArtifactValueTemplate::RecordField"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "\"event\":\"branch_selected\""),
            Diagnostics => ("docs/src/runtime-traces.md", "Mantle selected a typed runtime control-flow branch"),
            RunnableExample => ("examples/runtime_payload_projection_if.str", "assigned_phase == Ready"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_branches_on_received_record_field"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/payload_projection.rs", "runtime_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_payload_projection_if.str"),
            Documentation => ("docs/src/examples.md", "runtime_payload_projection_if.str"),
        ],
    ),
    feature!(
        "runtime-if-current-state-projection",
        "Runtime if over current state record fields",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_branches_on_current_record_field"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "assert_current_payload_phase_action_branch"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "ArtifactValueTemplate::RecordField"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_branches_on_current_record_field"),
            Diagnostics => ("docs/src/runtime-traces.md", "Mantle selected a typed runtime control-flow branch"),
            RunnableExample => ("examples/runtime_state_payload_projection_if.str", "held_phase == Ready"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_branches_on_current_record_field"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/state_payload_projection_if.rs", "runtime_state_payload_projection_if_rejects_unknown_projected_field_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_state_payload_projection_if.str"),
            Documentation => ("docs/src/examples.md", "runtime_state_payload_projection_if.str"),
        ],
    ),
    feature!(
        "runtime-if-final-next-state",
        "Final-position runtime if next-state selection",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_prefix_selected_next_state_branch"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "assert_final_if_guarded_loop_shape"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "scope\":\"next_state"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_rejects_nested_loop_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_prefix_selected_next_state_branch"),
            Diagnostics => ("docs/src/diagnostics.md", "statement-level if action nesting exceeds maximum depth"),
            RunnableExample => ("examples/runtime_final_if_guarded_loop.str", "enabled == True"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_prefix_selected_next_state_branch"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/final_if_loop_actions.rs", "runtime_final_if_loop_actions_rejects_nested_loop_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_final_if_guarded_loop.str"),
            Documentation => ("docs/src/examples.md", "runtime_final_if_guarded_loop.str"),
        ],
    ),
    feature!(
        "runtime-if-noop-branches",
        "Runtime if no-op branches",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_rejects_malformed_both_empty_branch_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            Diagnostics => ("docs/src/diagnostics.md", "statement-level if branches cannot both be empty"),
            RunnableExample => ("examples/runtime_guard_noop.str", "flag == True"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_branches_emit_selection_traces"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_guard_noop_rejects_malformed_both_empty_branch_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_guard_noop.str"),
            Documentation => ("docs/src/examples.md", "runtime_guard_noop.str"),
        ],
    ),
    feature!(
        "runtime-if-nested-action-branches",
        "Nested runtime if action branches",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            CheckerValidation => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "assert_nested_action_branch"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_rejects_action_nesting_above_limit_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            Diagnostics => ("docs/src/diagnostics.md", "runtime if branch cannot bind process references"),
            RunnableExample => ("examples/runtime_nested_if_actions.str", "primary == True"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_branch_through_typed_action_paths"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches/nested_if_actions.rs", "runtime_nested_if_actions_rejects_action_nesting_above_limit_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_nested_if_actions.str"),
            Documentation => ("docs/src/examples.md", "runtime_nested_if_actions.str"),
        ],
    ),
    feature!(
        "runtime-for-checked-lists",
        "Mantle-backed bounded runtime for over checked lists",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/validation_rejections.rs", "runtime_for_each_rejects_static_collection_source_folding"),
            CheckedIrLowering => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "CheckedAction::ForEach"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/codec/for_each_admission.rs", "admission_rejects_dynamic_for_each_non_list_collection"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/for_each_payload.rs", "runtime_for_each_iterates_over_payload_at_mantle_runtime"),
            Diagnostics => ("docs/src/diagnostics.md", "for loop collection must be a runtime list binding"),
            RunnableExample => ("examples/runtime_for_each.str", "for item in items"),
            PositiveTest => ("crates/mantle-runtime/src/tests/for_each_host.rs", "in_memory_host_executes_for_each_loop_in_collection_order"),
            NegativeTest => ("crates/mantle-runtime/src/run/tests/state_message_for_each_admission.rs", "runtime_rejects_loaded_dynamic_for_each_non_list_collection_before_artifact_loaded"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_for_each.str"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/collection_state.str", "Map<Phase,Phase,2>"),
            Documentation => ("docs/src/runtime-traces.md", "Runtime Loop Events"),
        ],
    ),
    feature!(
        "runtime-for-loop-branching",
        "Runtime for loop body branching",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_preflights_malformed_loop_bool_before_branch_effects"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            Diagnostics => ("docs/src/runtime-traces.md", "When a branch runs inside a bounded runtime loop body"),
            RunnableExample => ("examples/runtime_for_each_if.str", "for item in items"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_branching.rs", "runtime_for_each_if_branches_inside_loop_body_at_mantle_runtime"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_rejects_malformed_branch_send_target_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_for_each_if.str"),
            Documentation => ("docs/src/runtime-traces.md", "Runtime Loop Events"),
        ],
    ),
    feature!(
        "runtime-for-guarded-loops",
        "Runtime if guarded bounded loops",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_preflights_malformed_loop_bool_before_branch_effects"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            Diagnostics => ("docs/src/runtime-traces.md", "When a statement-level branch guards a bounded runtime loop"),
            RunnableExample => ("examples/runtime_guarded_for_each.str", "for item in items"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_loop.rs", "runtime_guarded_for_each_branches_loop_at_mantle_runtime"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_for_each_if_rejects_inactive_branch_condition_loop_element_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_guarded_for_each.str"),
            Documentation => ("docs/src/examples.md", "runtime_guarded_for_each.str"),
        ],
    ),
    feature!(
        "runtime-for-received-ref-routing",
        "Runtime for routing through received ProcessRef payloads",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop.rs", "runtime_guarded_ref_loop_routes_received_ref_inside_guarded_loop"),
            CheckerValidation => ("crates/strata/src/language/tests/process_refs.rs", "resolves_process_references_to_ids_before_artifact_encoding"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop.rs", "runtime_guarded_ref_loop_routes_received_ref_inside_guarded_loop"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_guarded_ref_loop_rejects_malformed_received_target_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop_jobs.rs", "runtime_guarded_ref_loop_jobs_routes_payload_values_through_received_ref"),
            Diagnostics => ("docs/src/runtime-reference.md", "process references still remain valid only as direct message payload bindings"),
            RunnableExample => ("examples/runtime_guarded_ref_loop_jobs.str", "Route(ProcessRef<Worker>)"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/guarded_ref_loop_jobs.rs", "runtime_guarded_ref_loop_jobs_routes_payload_values_through_received_ref"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_admission.rs", "runtime_guarded_ref_loop_rejects_malformed_received_target_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_guarded_ref_loop_jobs.str"),
            Documentation => ("docs/src/examples.md", "runtime_guarded_ref_loop_jobs.str"),
        ],
    ),
    feature!(
        "runtime-for-loop-element-projection",
        "Runtime for loop element record projection",
        Current,
        RuntimeBehavior,
        RUNTIME_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_routes_ready_phase_through_received_ref"),
            CheckerValidation => ("crates/strata/src/language/tests/runtime_for_each/basic_control_flow.rs", "runtime_for_each_checks_and_lowers_to_mantle_loop_control_flow"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "is_loop_element_projection_route"),
            ArtifactAdmission => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_rejects_unknown_projected_field_before_runtime"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_routes_ready_phase_through_received_ref"),
            Diagnostics => ("docs/src/diagnostics.md", "loop element binding ... cannot have process reference type"),
            RunnableExample => ("examples/runtime_loop_element_projection.str", "routed_phase == Ready"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_routes_ready_phase_through_received_ref"),
            NegativeTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_loop_execution/loop_element_projection.rs", "runtime_loop_element_projection_rejects_non_record_projection_source_before_runtime"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_loop_element_projection.str"),
            Documentation => ("docs/src/examples.md", "runtime_loop_element_projection.str"),
        ],
    ),
    feature!(
        "return-match-action-blocks",
        "Selected step return-match arms as typed action blocks",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/process_return_match_arm_bounded_assurance/tests.rs", "bounded_assurance_selected_arm_action_blocks_match_checked_ir_and_artifacts"),
            CheckerValidation => ("crates/strata/src/language/tests/process_return_match_arm_bounded_assurance/source.rs", "bounded model sequence"),
            CheckedIrLowering => ("crates/strata/src/language/tests/process_return_match_arm_bounded_assurance/assertions.rs", "checked_action_shapes"),
            ArtifactAdmission => ("crates/strata/src/language/tests/process_return_match_arm_prefix_invalid_templates.rs", "unselected return-match arm send payload template should be validated"),
            RuntimeExecution => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions/return_match_arm_action_block.rs", "process_return_match_arm_action_block_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "step return match arm cannot bind process reference"),
            RunnableExample => ("examples/process_return_match_arm_action_block.str", "return-match action-block uniform prefix"),
            PositiveTest => ("crates/strata/src/language/tests/process_return_match_arm_prefix_properties/tests.rs", "property_generated_selected_arm_action_block_shapes_lower_as_typed_actions"),
            NegativeTest => ("crates/strata/src/language/tests/process_return_match_arm_prefix.rs", "rejects_step_return_match_arm_process_ref_binding"),
            SourceToRuntimeGate => ("Justfile", "examples/process_return_match_arm_action_block.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/process_return_match_arm_action_block.str", "module process_return_match_arm_action_block_seed"),
            BoundedOrProperty => ("Justfile", "bounded-assurance-smoke"),
            Documentation => ("docs/src/development-gates.md", "selected `step return match`"),
        ],
    ),
    feature!(
        "typed-scalar-value-operators",
        "Typed scalar values and value operators",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_scalar_values.rs", "parses_typed_scalar_literals_and_operator_precedence"),
            CheckerValidation => ("crates/strata/src/language/tests/source_scalar_values.rs", "rejects_invalid_scalar_source_forms"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_scalar_values.rs", "lowers_runtime_bound_scalar_operators_as_typed_templates"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/scalar_templates.rs", "admission_accepts_typed_value_if_template"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/scalar_templates.rs", "runtime_evaluates_typed_value_if_template"),
            Diagnostics => ("docs/src/diagnostics.md", "numeric value literals require an explicit scalar suffix"),
            RunnableExample => ("examples/runtime_scalar_priority.str", "fn classify"),
            PositiveTest => ("crates/strata/src/language/tests/source_scalar_values.rs", "folds_concrete_scalar_bindings_records_lists_maps_and_if"),
            NegativeTest => ("crates/strata/src/language/tests/source_scalar_values.rs", "rejects_runtime_bound_static_zero_scalar_divisors"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_scalar_priority.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/runtime_scalar_priority.str", "module runtime_scalar_priority"),
            BoundedOrProperty => ("crates/strata/src/language/tests/source_scalar_bounded.rs", "bounded_scalar_expression_shapes_cover_bindings_collections_and_source_if"),
            Documentation => ("docs/src/language-reference.md", "Scalar Integer Values"),
        ],
    ),
    feature!(
        "typed-effect-outcomes",
        "Typed effect outcomes and commit-or-return boundaries",
        Current,
        RuntimeBehavior,
        RUNTIME_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/effect_outcomes/branch_patterns.rs", "checks_and_lowers_typed_effect_outcome_bindings_without_source_name_dispatch"),
            CheckerValidation => ("crates/strata/src/language/tests/effect_outcomes/static_rejections.rs", "rejects_spawn_outcome_annotation_without_process_ref_success_shape"),
            CheckedIrLowering => ("crates/strata/src/language/tests/effect_outcomes/branch_patterns.rs", "CheckedAction::SpawnOutcome"),
            ArtifactAdmission => ("crates/mantle-artifact/src/tests/effect_outcomes.rs", "validate_rejects_spawn_outcome_type_without_process_ref_success"),
            RuntimeExecution => ("crates/mantle-runtime/src/run/tests/effect_outcomes.rs", "runtime_spawn_outcome_commits_ok_after_acceptance"),
            Diagnostics => ("docs/src/diagnostics.md", "send outcome binding must have type Result<Unit,SendError<...>>"),
            RunnableExample => ("examples/effect_outcomes.str", "let spawn_result: Result<ProcessRef<Worker>,SpawnError<Unit>> = spawn Worker"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_effect_outcomes.rs", "effect_outcomes_check_build_run_and_bind_typed_commit_results"),
            NegativeTest => ("crates/strata/src/language/tests/effect_outcomes/static_rejections.rs", "rejects_spawn_outcome_as_state_because_success_carries_process_ref"),
            SourceToRuntimeGate => ("Justfile", "examples/effect_outcomes.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/effect_outcomes.str", "module effect_outcomes"),
            FuzzSeed => ("fuzz/seeds/mantle_artifact_decode/effect_outcomes.mta", "process.0.transition.0.action.0.kind=spawn_outcome"),
            FuzzSeed => ("fuzz/seeds/mantle_runtime_from_source/effect_outcomes.str", "module effect_outcomes"),
            BoundedOrProperty => ("crates/strata/src/language/tests/effect_outcomes/static_rejections.rs", "bounded_effect_outcome_state_admission_matches_commit_or_return_model"),
            Documentation => ("docs/src/runtime-reference.md", "Typed Effect Outcomes"),
        ],
    ),
    feature!(
        "runtime-observability",
        "Runtime observability trace boundary",
        Current,
        RuntimeBehavior,
        RUNTIME_OBSERVABILITY_REQUIREMENTS,
        [
            RuntimeExecution => ("crates/mantle-runtime/src/tests/runtime_boundaries.rs", "run_artifact_path_writes_trace_for_current_directory_artifact"),
            Diagnostics => ("docs/src/runtime-traces.md", "Runtime dispatch always uses the numeric `message_id`"),
            RunnableExample => ("examples/actor_sequence.str", "actor_sequence"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/basic_runtime.rs", "actor_sequence_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/mantle-runtime/src/tests/runtime_boundaries.rs", "runtime_rejects_trace_limit_exhaustion"),
            SourceToRuntimeGate => ("Justfile", "examples/actor_sequence.str"),
            Documentation => ("docs/src/runtime-traces.md", "The trace is evidence that Mantle admitted and executed the artifact"),
        ],
    ),
];
