use crate::model::{Feature, requirements::*};

pub(crate) const FEATURES: &[Feature] = &[
    feature!(
        "source-unit-top-level-items",
        "Source unit and top-level item declarations",
        Current,
        SourceOnly,
        SOURCE_SYNTAX_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/examples.rs", "fn parses_and_checks_hello()"),
            CheckerValidation => ("crates/strata/src/language/tests/examples.rs", "checked.module().name.as_str()"),
            Diagnostics => ("docs/src/diagnostics.md", "expected protocol, port, component, composition, record, enum, function, or proc declaration"),
            RunnableExample => ("examples/hello.str", "module hello;"),
            PositiveTest => ("crates/strata/src/language/tests/examples.rs", "parses_and_checks_hello"),
            NegativeTest => ("crates/strata/src/language/tests/syntax.rs", "rejects_duplicate_process_members"),
            Documentation => ("docs/src/language-reference.md", "| Source unit |"),
        ],
    ),
    feature!(
        "source-unit-imports",
        "Typed source-unit imports and dependency graph",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_units.rs", "parser_accepts_imports_before_declarations"),
            CheckerValidation => ("crates/strata/src/language/tests/source_units.rs", "source_program_checks_lowers_cross_unit_records_functions_and_processes"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_units.rs", "imported Worker send should lower as typed artifact IDs"),
            Diagnostics => ("docs/src/diagnostics.md", "references ... without importing ..."),
            RunnableExample => ("examples/imports_main.str", "import imports_types;"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_units.rs", "imports_main_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/source_units.rs", "source_program_rejects_reachable_but_unimported_symbols"),
            SourceToRuntimeGate => ("Justfile", "examples/imports_main.str"),
            FuzzSeed => ("fuzz/seeds/strata_source_program_check_lower/imports_main.strpack", "module imports_worker_seed"),
            BoundedOrProperty => ("crates/strata/src/language/tests/source_units_property.rs", "property_generated_dependency_graphs_cover_order_cycles_duplicates_and_resolution"),
            Documentation => ("docs/src/language-reference.md", "Imports use the narrow form"),
        ],
    ),
    feature!(
        "records-enums-immutable-values",
        "Records, enums, and immutable source values",
        Current,
        SourceOnly,
        SOURCE_SYNTAX_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/syntax.rs", "parses_and_checks_immutable_record_state_constructors"),
            CheckerValidation => ("crates/strata/src/language/tests/syntax.rs", "checked_state_labels"),
            Diagnostics => ("docs/src/diagnostics.md", "assignment statements are not supported"),
            RunnableExample => ("examples/state_payload_enum.str", "enum WorkerState"),
            PositiveTest => ("crates/strata/src/language/tests/syntax.rs", "parses_and_checks_immutable_record_state_constructors"),
            NegativeTest => ("crates/strata/src/language/tests/syntax.rs", "rejects_mutable_record_field_declarations"),
            Documentation => ("docs/src/language-reference.md", "Records define structured state values"),
        ],
    ),
    feature!(
        "pure-source-functions-and-calls",
        "Pure source functions and source function calls",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_core.rs", "parses_checks_and_lowers_source_functions_with_pattern_matching"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_core.rs", "check_module(module).expect"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_function_core.rs", "!encoded.contains(\"readiness_sig\")"),
            Diagnostics => ("docs/src/diagnostics.md", "function ... must not declare effects"),
            RunnableExample => ("examples/function_match.str", "fn readiness_sig"),
            PositiveTest => ("crates/strata/src/language/tests/source_function_core.rs", "parses_checks_and_lowers_source_functions_with_pattern_matching"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_core.rs", "rejects_source_function_statements"),
            SourceToRuntimeGate => ("Justfile", "examples/function_match.str"),
            Documentation => ("docs/src/language-reference.md", "| Top-level functions |"),
        ],
    ),
    feature!(
        "source-function-whole-body-match",
        "Pure source function whole-body match",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_core.rs", "parses_checks_and_lowers_source_functions_with_pattern_matching"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_patterns.rs", "checks_source_function_match_wildcard_covers_payload_variant"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_function_core.rs", "!encoded.contains(\"readiness_body\")"),
            Diagnostics => ("docs/src/diagnostics.md", "match has no matching pattern for ..."),
            RunnableExample => ("examples/function_match.str", "fn readiness_body"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "function_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_patterns.rs", "rejects_non_exhaustive_source_function_match_body"),
            SourceToRuntimeGate => ("Justfile", "examples/function_match.str"),
            Documentation => ("docs/src/language-reference.md", "A function may also use a whole-body match"),
        ],
    ),
    feature!(
        "core-bool-builtins",
        "Core Bool, True, and False built-ins",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/core_bool.rs", "core_bool_is_available_without_source_declaration"),
            CheckerValidation => ("crates/strata/src/language/tests/core_bool.rs", "core_bool_rejects_conflicting_user_declarations"),
            CheckedIrLowering => ("crates/strata/src/language/tests/core_bool.rs", "checked IR should contain core Bool type"),
            Diagnostics => ("docs/src/diagnostics.md", "conflicts with core Bool value constructor"),
            RunnableExample => ("examples/function_if_else.str", "fn choose(flag: Bool)"),
            PositiveTest => ("crates/strata/src/language/tests/core_bool.rs", "core_bool_is_available_without_source_declaration"),
            NegativeTest => ("crates/strata/src/language/tests/core_bool.rs", "core_bool_rejects_conflicting_user_declarations"),
            SourceToRuntimeGate => ("Justfile", "examples/function_if_else.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/function_return_if_block.str", "fn choose"),
            BoundedOrProperty => ("crates/strata/src/language/tests/core_bool.rs", "core_bool_lowers_deterministically_across_declaration_order"),
            Documentation => ("docs/src/language-reference.md", "cannot be redeclared by user"),
        ],
    ),
    feature!(
        "source-function-return-if",
        "Pure source function return-if selection",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_if_else.rs", "parses_checks_and_lowers_source_function_braced_return_if_else"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_if_else.rs", "braced source return-if should check"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_function_if_else.rs", "!encoded.contains(\"choose_block\")"),
            Diagnostics => ("docs/src/diagnostics.md", "source function ... return-if ... branch must not perform statements"),
            RunnableExample => ("examples/function_if_else.str", "fn choose"),
            PositiveTest => ("crates/strata/src/language/tests/source_function_if_else.rs", "parses_checks_and_lowers_source_function_braced_return_if_else"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_if_else.rs", "rejects_braced_return_if_branch_statements_in_source_function"),
            SourceToRuntimeGate => ("Justfile", "examples/function_if_else.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/function_return_if_block.str", "fn choose"),
            BoundedOrProperty => ("crates/strata/src/language/tests/source_function_if_else.rs", "property_generated_braced_return_if_selects_concrete_source_branch"),
            Documentation => ("docs/src/language-reference.md", "| Pure conditionals |"),
        ],
    ),
    feature!(
        "source-function-local-bindings",
        "Immutable source-local function bindings",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_FUZZ_BOUNDED_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_local_bindings.rs", "Statement::LetValue"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_local_bindings.rs", "parses_checks_and_lowers_immutable_source_local_bindings"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_function_local_bindings.rs", "must not lower into executable artifact meaning"),
            Diagnostics => ("docs/src/diagnostics.md", "source-local binding ... value must produce ..."),
            RunnableExample => ("examples/function_local_bindings.str", "let current_local"),
            PositiveTest => ("crates/strata/src/language/tests/source_function_local_bindings.rs", "parses_checks_and_lowers_immutable_source_local_bindings"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_local_bindings_authority.rs", "rejects_process_reference_carrier_enum_source_local_binding"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_local_bindings/shadowing.rs", "rejects_source_function_binding_parameter_shadowing_process_ref_binding"),
            SourceToRuntimeGate => ("Justfile", "examples/function_local_bindings.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/function_local_bindings.str", "module function_local_bindings_seed"),
            BoundedOrProperty => ("crates/strata/src/language/tests/source_function_local_bindings.rs", "bounded_alias_chains_match_direct_source_function_result"),
            Documentation => ("docs/src/language-reference.md", "| Source-local bindings |"),
        ],
    ),
    feature!(
        "source-function-return-match",
        "Pure source function return-match expressions",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_patterns.rs", "checks_source_function_return_match_expression_with_payload_binding"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_patterns.rs", "check_source(source).expect(\"source function return match should check\")"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "function_return_match_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "return match must handle variant ..."),
            RunnableExample => ("examples/function_return_match.str", "return match work"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "function_return_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_patterns.rs", "rejects_non_exhaustive_source_function_return_match_expression"),
            SourceToRuntimeGate => ("Justfile", "examples/function_return_match.str"),
            Documentation => ("docs/src/language-reference.md", "function return-match expressions"),
        ],
    ),
    feature!(
        "source-function-record-patterns",
        "Pure source function record pattern destructuring",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_record_patterns/body_match.rs", "checks_source_function_body_match_record_destructuring_pattern"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_record_patterns/body_match.rs", "checks_source_function_record_patterns_after_payload_expansion"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "function_record_body_match_checks_builds_and_runs_on_mantle"),
            Diagnostics => ("docs/src/diagnostics.md", "record pattern ... has no field ..."),
            RunnableExample => ("examples/function_record_body_match.str", "Job { phase }"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "function_record_body_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_record_patterns/body_match.rs", "rejects_source_function_body_match_record_unknown_field"),
            SourceToRuntimeGate => ("Justfile", "examples/function_record_body_match.str"),
            Documentation => ("docs/src/language-reference.md", "Whole-body function matches may also destructure"),
        ],
    ),
    feature!(
        "source-function-list-map-patterns",
        "Pure source function list and map pattern destructuring",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_FUZZ_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_collection_patterns/function_surfaces.rs", "checks_source_function_list_and_map_patterns"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_collection_patterns/list_rest_patterns.rs", "checks_source_function_list_rest_surfaces"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_function_collection_patterns/function_surfaces.rs", "lower_to_artifact(&checked, source)"),
            Diagnostics => ("docs/src/diagnostics.md", "requires a concrete list value argument"),
            RunnableExample => ("examples/function_collection_match.str", "List<Phase,2>"),
            PositiveTest => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/source_functions.rs", "function_collection_match_checks_builds_and_runs_on_mantle"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_collection_patterns/non_concrete_dispatch.rs", "rejects_source_function_list_body_match_non_concrete_scrutinee"),
            SourceToRuntimeGate => ("Justfile", "examples/function_collection_match.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/collection_state.str", "List<Phase,2>"),
            Documentation => ("docs/src/language-reference.md", "Whole-body function matches can destructure exact list patterns"),
        ],
    ),
    feature!(
        "source-patterns-and-return-match",
        "Function patterns, return-match, and record/list/map destructuring",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_FUZZ_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/nested_pattern_destructuring/source_functions.rs", "source_functions_bind_nested_patterns_in_signature_body_and_return_match"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_collection_patterns/function_surfaces.rs", "checks_source_function_list_and_map_patterns"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_function_collection_patterns/function_surfaces.rs", "lower_to_artifact(&checked, source)"),
            Diagnostics => ("docs/src/diagnostics.md", "requires a concrete list value argument"),
            RunnableExample => ("examples/nested_patterns.str", "AssignEnvelope(Assign(Job { phase }))"),
            PositiveTest => ("crates/strata/src/language/tests/source_function_patterns.rs", "checks_source_function_return_match_expression_with_payload_binding"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_patterns.rs", "rejects_non_exhaustive_source_function_return_match_expression"),
            SourceToRuntimeGate => ("Justfile", "examples/nested_patterns.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/nested_patterns.str", "module nested_patterns"),
            Documentation => ("docs/src/syntax-reference.md", "function return-match expressions"),
        ],
    ),
    feature!(
        "static-map-keys-and-collections",
        "Static map keys and bounded immutable collections",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_FUZZ_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_function_collection_patterns/function_surfaces.rs", "checks_source_function_list_and_map_patterns"),
            CheckerValidation => ("crates/strata/src/language/tests/source_function_collection_patterns/template_keys.rs", "rejects_runtime_dependent_map_key_state_template"),
            CheckedIrLowering => ("crates/strata/src/language/tests/source_function_collection_patterns/function_surfaces.rs", "expected a map next-state template using the received payload"),
            Diagnostics => ("docs/src/diagnostics.md", "map pattern keys must be static source values"),
            RunnableExample => ("examples/collection_state.str", "Map<Phase,Phase,2>"),
            PositiveTest => ("crates/strata/src/language/tests/source_function_collection_patterns/function_surfaces.rs", "checks_source_function_subset_map_patterns"),
            NegativeTest => ("crates/strata/src/language/tests/source_function_collection_patterns/template_keys.rs", "rejects_runtime_dependent_map_key_state_template"),
            SourceToRuntimeGate => ("Justfile", "examples/collection_state.str"),
            FuzzSeed => ("fuzz/seeds/strata_parse_check_lower/collection_state.str", "Map<Phase,Phase,2>"),
            Documentation => ("docs/src/syntax-reference.md", "List and map constructors are explicit"),
        ],
    ),
    feature!(
        "bool-equality-predicates",
        "Bool, equality, and composed predicate forms",
        Current,
        CheckerLowering,
        CHECKER_LOWERING_REQUIREMENTS,
        [
            ParserCoverage => ("crates/strata/src/language/tests/source_value_equality.rs", "folds_concrete_bool_and_fieldless_enum_equality"),
            CheckerValidation => ("crates/strata/src/language/tests/source_value_equality.rs", "folds_concrete_boolean_predicate_composition"),
            CheckedIrLowering => ("crates/strata-mantle-acceptance/tests/source_to_runtime_gates/runtime_branches.rs", "runtime_if_else_composed_predicate_branches_on_payload_at_mantle_runtime"),
            Diagnostics => ("docs/src/diagnostics.md", "equality operands must be Bool, String, Bytes, scalar values, or fieldless enum values"),
            RunnableExample => ("examples/runtime_if_else.str", "if (flag == True)"),
            PositiveTest => ("crates/strata/src/language/tests/source_value_equality.rs", "folds_concrete_boolean_predicate_composition"),
            NegativeTest => ("crates/strata/src/language/tests/source_value_equality.rs", "rejects_source_equality_invalid_operand_types"),
            SourceToRuntimeGate => ("Justfile", "examples/runtime_if_else.str"),
            Documentation => ("docs/src/syntax-reference.md", "Typed equality predicates are deliberately narrow"),
        ],
    ),
];
